# Generated by Django 3.0 on 2019-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField()),
                ('img_html', models.TextField()),
                ('ingredient_name', models.TextField()),
                ('ingredient_quantity', models.TextField()),
                ('setp_text', models.TextField()),
            ],
        ),
    ]
